import type { Metadata } from "next";
import Link from "next/link";
import MarketingPageShell from "@/components/layout/MarketingPageShell";

export const metadata: Metadata = {
  title: "Terms of Service — Life Decision Engine",
  description:
    "The terms under which you may use Life Decision Engine: service scope, user conduct, disclaimers, payments, and liability.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <MarketingPageShell
      eyebrow="Legal"
      title="Terms of Service"
      subtitle={
        <p>
          Last updated April 2026. By using this site, you agree to the terms
          below. These terms apply to the live service (the home analyzer,
          blog, FAQ, experts directory, and related pages). This is not legal
          advice; adapt with counsel if you fork the project.
        </p>
      }
    >
      <div className="max-w-3xl space-y-8 text-sm leading-relaxed text-[rgb(var(--ink-soft))]">
        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            1. What the service is
          </h2>
          <p className="mt-2">
            <strong className="text-[rgb(var(--ink))]">
              Life Decision Engine
            </strong>{" "}
            (“the service”, “we”, “us”) provides a structured
            decision-analysis workspace, supporting content (blog, FAQ), and
            links to third-party professionals. The service is informational
            and organizational. It is not a medical, legal, financial, or
            therapeutic service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            2. Who may use it
          </h2>
          <p className="mt-2">
            You must be at least 13 years old, or the minimum age of digital
            consent in your jurisdiction, whichever is greater. If you use the
            service on behalf of an organization, you confirm that you are
            authorized to accept these terms for that organization.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            3. Acceptable use
          </h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 ps-5">
            <li>Submit content that is illegal, abusive, or violates others’ rights.</li>
            <li>Attempt to breach security, scrape data, or disrupt service.</li>
            <li>
              Use the service to make decisions that require a professional
              (e.g. medical symptoms, contract disputes, clinical crises)
              without also consulting a qualified human.
            </li>
            <li>
              Resell, white-label, or redistribute the output as if it were
              professional advice.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            4. AI-generated content
          </h2>
          <p className="mt-2">
            If AI features are enabled, outputs are generated by models
            (e.g. OpenAI) based on your input. AI outputs can be inaccurate,
            incomplete, or out-of-date. You are responsible for evaluating
            the output before acting on it. The service does not guarantee
            that AI outputs are suitable for any particular purpose.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            5. Experts directory
          </h2>
          <p className="mt-2">
            Listings in the{" "}
            <Link
              href="/experts"
              className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
            >
              experts directory
            </Link>{" "}
            are informational. We do not employ the listed professionals and
            do not warrant their qualifications, availability, or outcomes of
            any engagement. Your relationship with a professional is directly
            between you and them, subject to their terms and licensure.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            6. Payments (Premium & bookings)
          </h2>
          <p className="mt-2">
            Paid features, where active, are processed by{" "}
            <strong className="text-[rgb(var(--ink))]">Stripe</strong>. By
            purchasing, you also accept Stripe’s terms. Recurring charges
            continue until you cancel. Refund eligibility, if any, is
            described on the{" "}
            <Link
              href="/pricing"
              className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
            >
              pricing
            </Link>{" "}
            page or confirmed at checkout.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            7. Advertising
          </h2>
          <p className="mt-2">
            Some pages may display ads served by{" "}
            <strong className="text-[rgb(var(--ink))]">Google AdSense</strong>{" "}
            or similar networks. Ads are clearly marked where regulations
            require. See the{" "}
            <Link
              href="/privacy"
              className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
            >
              Privacy Policy
            </Link>{" "}
            for how ad partners process your data.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            8. Intellectual property
          </h2>
          <p className="mt-2">
            The site, its design, copy, and code are owned by the operator
            unless otherwise noted. You retain ownership of text you submit
            into the analyzer. You grant us a limited licence to process that
            text solely to provide the service (including forwarding to an AI
            provider, if enabled).
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            9. Disclaimers
          </h2>
          <p className="mt-2">
            The service is provided{" "}
            <em>“as is” and “as available.”</em> To the fullest
            extent permitted by law, we disclaim all warranties, express or
            implied, including fitness for a particular purpose. Decisions
            based on the service are your responsibility.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            10. Limitation of liability
          </h2>
          <p className="mt-2">
            To the fullest extent permitted by law, our aggregate liability
            for claims arising from or related to the service is limited to
            the amounts you paid us in the 12 months preceding the claim, or
            USD 50 if you paid nothing. We are not liable for indirect,
            incidental, or consequential damages.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            11. Termination
          </h2>
          <p className="mt-2">
            We may suspend or terminate access to the service if you breach
            these terms or use the service in a way that risks harm to us or
            others. You may stop using the service at any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            12. Changes to these terms
          </h2>
          <p className="mt-2">
            We may update these terms to reflect new features, legal
            requirements, or operational changes. Material changes will be
            flagged on this page with an updated date. Continued use after a
            change means you accept the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            13. Contact
          </h2>
          <p className="mt-2">
            For questions about these terms, see the{" "}
            <Link
              href="/contact"
              className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
            >
              contact
            </Link>{" "}
            page.
          </p>
        </section>

        <p>
          <Link
            href="/"
            className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
          >
            ← Back to home
          </Link>
        </p>
      </div>
    </MarketingPageShell>
  );
}
