import type { Metadata } from "next";
import Link from "next/link";
import MarketingPageShell from "@/components/layout/MarketingPageShell";

export const metadata: Metadata = {
  title: "Disclaimer — Life Decision Engine",
  description:
    "Life Decision Engine is an informational decision-support tool, not a substitute for medical, legal, or financial advice. Read our full disclaimer and use-of-AI notice.",
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <MarketingPageShell
      eyebrow="Legal"
      title="Disclaimer"
      subtitle={
        <p>
          Life Decision Engine is an informational, decision-support workspace.
          It is not a medical, legal, therapeutic, or financial service. Read
          the notices below before acting on anything you see on this site.
        </p>
      }
    >
      <div className="max-w-3xl space-y-8 text-sm leading-relaxed text-[rgb(var(--ink-soft))]">
        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            No professional advice
          </h2>
          <p className="mt-2">
            Nothing on this site — including analyzer outputs, articles, FAQ
            answers, or expert listings — constitutes professional medical,
            psychological, psychiatric, legal, tax, accounting, investment,
            or financial-planning advice. Content is provided for general
            educational and decision-framing purposes only. Your situation
            has specifics we cannot know. Always consult a qualified,
            licensed professional in your jurisdiction before making
            decisions that carry clinical, legal, or financial consequence.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            AI-generated outputs
          </h2>
          <p className="mt-2">
            When AI analysis is enabled, outputs are generated by large
            language models based on your input. Large language models are
            known to make mistakes, including confidently stating things that
            are incorrect, outdated, or incomplete. Treat AI outputs as a
            structured <em>starting point</em> for your own thinking, not a
            verdict. We do not guarantee any specific outcome from following
            suggestions produced by the engine.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            Experts directory
          </h2>
          <p className="mt-2">
            Professionals listed in the{" "}
            <Link
              href="/experts"
              className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
            >
              experts directory
            </Link>{" "}
            are independent practitioners. We do not employ them, supervise
            their practice, or guarantee their qualifications, availability,
            or the outcomes of any engagement. Any relationship you form
            with a listed professional is directly between you and them,
            subject to their own terms, policies, and licensure requirements
            in your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            Not an emergency service
          </h2>
          <p className="mt-2">
            If you are experiencing a mental-health crisis, thoughts of
            self-harm, or a medical, legal, or safety emergency,{" "}
            <strong className="text-[rgb(var(--ink))]">
              do not use this site
            </strong>
            . Contact your local emergency number, a licensed professional,
            or a recognised crisis line in your country. A list of regional
            crisis resources can be found through organisations such as the
            World Health Organization and Befrienders Worldwide.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            Financial, investment, and tax decisions
          </h2>
          <p className="mt-2">
            Any examples, scenarios, rule-of-thumb figures, or frameworks
            shown on this site are for illustration only. Past performance,
            historical averages, and general financial heuristics do not
            guarantee future results. Tax and financial-planning rules vary
            by jurisdiction and change often. Before making a decision that
            affects your income, savings, taxes, investments, business, or
            debt, consult a licensed financial advisor, accountant, tax
            professional, or attorney qualified in your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            Third-party links
          </h2>
          <p className="mt-2">
            The site may contain links to third-party websites and services
            (including Stripe, Google, and partners we write about). We do
            not control those sites and are not responsible for their
            content, availability, or privacy practices. Following an
            external link is at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            Accuracy of information
          </h2>
          <p className="mt-2">
            We put real effort into making our articles and analyzer
            frameworks accurate, but we make no representation or warranty,
            express or implied, about the completeness, accuracy,
            reliability, suitability, or availability of any information on
            the site for any purpose. Any reliance you place on such
            information is therefore strictly at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[rgb(var(--ink))]">
            Related documents
          </h2>
          <ul className="mt-2 list-disc space-y-1.5 ps-5">
            <li>
              <Link
                href="/terms"
                className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
              >
                Terms of Service
              </Link>
            </li>
            <li>
              <Link
                href="/privacy"
                className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
              >
                Privacy Policy
              </Link>
            </li>
            <li>
              <Link
                href="/editorial-standards"
                className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
              >
                Editorial Standards
              </Link>
            </li>
            <li>
              <Link
                href="/editorial-team"
                className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
              >
                Editorial Team
              </Link>
            </li>
          </ul>
        </section>

        <p>
          <Link
            href="/"
            className="font-medium text-[rgb(var(--accent-2))] underline-offset-2 hover:underline"
          >
            ← Back to home
          </Link>
        </p>
      </div>
    </MarketingPageShell>
  );
}
